In [329]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#loading the data into a dataframe
df = pd.read_csv('weather.csv')
df2 = pd.read_csv('weather.csv')

In [330]:
import numpy as np
from sklearn                        import metrics, svm
from sklearn.linear_model           import LinearRegression
from sklearn.linear_model           import LogisticRegression
from sklearn.tree                   import DecisionTreeClassifier
from sklearn.neighbors              import KNeighborsClassifier
from sklearn.discriminant_analysis  import LinearDiscriminantAnalysis
from sklearn.naive_bayes            import GaussianNB
from sklearn.svm                    import SVC

In [331]:
one_hot_encoded_data = pd.get_dummies(df, columns = ['Rainfall', 'Evaporation'])
df = one_hot_encoded_data
df.insert(0, 'MaxTemp', df.pop('MaxTemp'))
X = df.iloc[:,1:4]
Y = df.iloc[:,0]
df

,MaxTemp,Day,Rainfall_0.0,Rainfall_0.2,Rainfall_0.4,Rainfall_0.6,Rainfall_0.8,Rainfall_1.0,Rainfall_1.2,Rainfall_1.4,...,Evaporation_9.4,Evaporation_9.6,Evaporation_10.0,Evaporation_10.2,Evaporation_10.4,Evaporation_11.4,Evaporation_11.6,Evaporation_12.4,Evaporation_12.6,Evaporation_13.8
0,24.3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,26.9,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,23.4,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,15.5,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,16.1,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,30.7,362,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
362,28.4,363,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
363,19.9,364,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
364,26.9,365,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
365,30.2,366,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [332]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [333]:
from sklearn import linear_model

regr = linear_model.LinearRegression()
regr.fit(X_train, Y_train)

y_pred = regr.predict(X_test)

In [334]:
from sklearn.metrics import mean_squared_error

In [335]:
#error for each model on taking the entire dataset
clf = LogisticRegression()
clf.fit(X_train, Y_train.astype(int))
print("LogisticRegression")
y_pred= clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = DecisionTreeClassifier()
clf.fit(X_train, Y_train.astype(int))
print("DecisionTreeClassifier")
y_pred= clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = KNeighborsClassifier()
clf.fit(X_train, Y_train.astype(int))
print("KNeighborsClassifier")
y_pred = clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = LinearDiscriminantAnalysis()
clf.fit(X_train, Y_train.astype(int))
print("LinearDiscriminantAnalysis")
y_pred = clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = GaussianNB()
clf.fit(X_train, Y_train.astype(int))
print("GaussianNB")
y_pred = clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = SVC()
clf.fit(X_train, Y_train.astype(int))
print("SVC")
y_pred = clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

LogisticRegression
6.025407914866888
DecisionTreeClassifier
3.6532288569265794
KNeighborsClassifier
4.450341620655715
LinearDiscriminantAnalysis
5.611775746323709
GaussianNB
6.896150512560751
SVC
5.531983174037846

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [336]:
del df2['Rainfall']
del df2['Evaporation']

In [337]:

X = df2.iloc[:,0]
Y = df2.iloc[:,1]
X = X.values.reshape(-1,1)
Y = Y.values.reshape(-1,1)

In [338]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [339]:
from sklearn.metrics import mean_squared_error

In [340]:
#error when taking only Max Temperature and Days
clf = LogisticRegression()
clf.fit(X_train, Y_train.astype(int))
print("LogisticRegression")
y_pred= clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = DecisionTreeClassifier()
clf.fit(X_train, Y_train.astype(int))
print("DecisionTreeClassifier")
y_pred= clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = KNeighborsClassifier()
clf.fit(X_train, Y_train.astype(int))
print("KNeighborsClassifier")
y_pred = clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = LinearDiscriminantAnalysis()
clf.fit(X_train, Y_train.astype(int))
print("LinearDiscriminantAnalysis")
y_pred = clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = GaussianNB()
clf.fit(X_train, Y_train.astype(int))
print("GaussianNB")
y_pred = clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

clf = SVC()
clf.fit(X_train, Y_train.astype(int))
print("SVC")
y_pred = clf.predict(X_test)
print(mean_squared_error(Y_test, y_pred, squared=False))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression
5.458207308908945
DecisionTreeClassifier
3.2470568794492003
KNeighborsClassifier
4.415895734178417
LinearDiscriminantAnalysis
5.458207308908945
GaussianNB
5.672849038729677
SVC
5.184970483900456

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)